export const images = {
  logo: '/images/saba_logo.png',
  hero: '/images/hero.png',
  auto: '/images/auto.png',
  home: '/images/home.png',
  business: '/images/business.png',
  boat: '/images/boat.png',
  team: '/images/team.png',
  renters: '/images/renters.png',
  condo: '/images/condo.png',
  flood: '/images/flood.png',
  life: '/images/life.png',
  about: '/images/about.png',
  carriers: {
    safetyInsurance: '/images/carriers/safety-insurance.png',
    mapfre: '/images/carriers/mapfre.png',
    libertyMutual: '/images/carriers/liberty-mutual.png',
    travelers: '/images/carriers/travelers.png',
    progressive: '/images/carriers/progressive.png',
    hanover: '/images/carriers/hanover.png',
    plymouthRock: '/images/carriers/plymouth-rock.png',
    concordGroup: '/images/carriers/concord-group.png',
    quincyMutual: '/images/carriers/quincy-mutual.png',
    safeco: '/images/carriers/safeco.png',
    stillwater: '/images/carriers/stillwater.png',
    uticaFirst: '/images/carriers/utica-first.png',
    providenceMutual: '/images/carriers/providence-mutual.png',
    geico: '/images/carriers/geico.png',
    foremost: '/images/carriers/foremost.png',
    berkshireHathawayGuard: '/images/carriers/berkshire-hathaway-guard.png',
  },
};
